In [1]:
import pandas as pd
import numpy as np

In [21]:
file_path = r"F:\Mehak Fatima\Farm Analytics\Data\Raw Data Crops\punjab_crop_share_vs_pakistan.csv"

raw = pd.read_csv(file_path, header=None)

raw.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,Crop/Indicators,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19,2019-20
1,Wheat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Area (""11000"" Hectares)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Pakistan,"8,550","9,046","9,132","8,901","8,650","8,660","9,199","9,206","9,224","8,973","8,797","8,805","9,168"
4,Punjab,"6,402","6,836","6,914","6,691","6,483","6,511","6,901","6,980","6,914","6,660","6,560","6,496","6,515"
5,Punjab as % share of Pakistan,75,76,76,75,75,75,75,76,75,74,75,74,71
6,"Production (""11000""M.tons)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Pakistan,"20,959","24,033","23,311","25,214","23,473","24,211","25,979","25,086","25,633","26,674","25,076","24,349","25,248"
8,Punjab,"15,607","18,420","17,919","19,041","17,739","18,585","19,739","19,282","19,527","20,466","19,179","18,377","19,402"
9,Punjab as % share\nof Pakistan,74,77,77,76,76,77,76,77,76,77,76,75,77
10,Rice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"Area (""11000"" Hectares)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Pakistan,"2,515","2,963","2,883","2,365","2,571","2,309","2,789","2,891","2,740","2,724","2,901","2,814","3,034"
13,Punjab,"1,724","1,978","1,932","1,767","1,714","1,711","1,809","1,878","1,780","1,738","1,841","1,904","2,029"
14,Punjab as % share of Pakistan,69,67,67,75,67,74,65,65,65,64,63,68,67

In [22]:
raw.shape

(109, 14)

In [23]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       109 non-null    object
 1   1       73 non-null     object
 2   2       73 non-null     object
 3   3       73 non-null     object
 4   4       73 non-null     object
 5   5       73 non-null     object
 6   6       73 non-null     object
 7   7       73 non-null     object
 8   8       73 non-null     object
 9   9       73 non-null     object
 10  10      73 non-null     object
 11  11      71 non-null     object
 12  12      72 non-null     object
 13  13      72 non-null     object
dtypes: object(14)
memory usage: 12.1+ KB

In [24]:
years = raw.iloc[0, 1:].tolist()

years

['2007-08',
 '2008-09',
 '2009-10',
 '2010-11',
 '2011-12',
 '2012-13',
 '2013-14',
 '2014-15',
 '2015-16',
 '2016-17',
 '2017-18',
 '2018-19',
 '2019-20']

In [25]:
crops = [
    "Wheat",
    "Rice",
    "Cotton",
    "Sugarcane",
    "Maize",
    "Gram",
    "Jowar",
    "Barley",
    "Rapeseed & Mustard",
    "Tobacco",
    "Sesamum",
    "Bajra"
]

crops

['Wheat',
 'Rice',
 'Cotton',
 'Sugarcane',
 'Maize',
 'Gram',
 'Jowar',
 'Barley',
 'Rapeseed & Mustard',
 'Tobacco',
 'Sesamum',
 'Bajra']

In [27]:
records = []

current_crop = None
current_metric = None

for i in range(1, len(raw)):
    
    label = str(raw.iloc[i, 0]).strip()
    
    # Crop
    if label in crops:
        current_crop = label
        current_metric = None
        continue
    
    # Metric
    if label.startswith("Area"):
        current_metric = "Area"
        continue
    
    if label.startswith("Production"):
        current_metric = "Production"
        continue
    
    # Geography
    if label in ["Pakistan", "Punjab"]:
        geography = label
        metric_name = current_metric
        
    elif "share" in label.lower():
        geography = "Punjab"
        metric_name = current_metric + " Share"
        
    else:
        continue
    
    # Years ke values
    for j, year in enumerate(years, start=1):
        
        value = raw.iloc[i, j]
        
        records.append({
            "Fiscal Year": year,
            "Crop": current_crop,
            "Metric": metric_name,
            "Geography": geography,
            "Value": value
        })

In [28]:
df = pd.DataFrame(records)

df.head(20)

   Fiscal Year   Crop Metric Geography  Value
0      2007-08  Wheat   Area  Pakistan  8,550
1      2008-09  Wheat   Area  Pakistan  9,046
2      2009-10  Wheat   Area  Pakistan  9,132
3      2010-11  Wheat   Area  Pakistan  8,901
4      2011-12  Wheat   Area  Pakistan  8,650
5      2012-13  Wheat   Area  Pakistan  8,660
6      2013-14  Wheat   Area  Pakistan  9,199
7      2014-15  Wheat   Area  Pakistan  9,206
8      2015-16  Wheat   Area  Pakistan  9,224
9      2016-17  Wheat   Area  Pakistan  8,973
10     2017-18  Wheat   Area  Pakistan  8,797
11     2018-19  Wheat   Area  Pakistan  8,805
12     2019-20  Wheat   Area  Pakistan  9,168
13     2007-08  Wheat   Area    Punjab  6,402
14     2008-09  Wheat   Area    Punjab  6,836
15     2009-10  Wheat   Area    Punjab  6,914
16     2010-11  Wheat   Area    Punjab  6,691
17     2011-12  Wheat   Area    Punjab  6,483
18     2012-13  Wheat   Area    Punjab  6,511
19     2013-14  Wheat   Area    Punjab  6,901

In [29]:
df["Value"] = (
    df["Value"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .replace("-", np.nan)
)

df["Value"] = pd.to_numeric(df["Value"], errors="coerce")

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 936 entries, 0 to 935
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fiscal Year  936 non-null    object
 1   Crop         936 non-null    object
 2   Metric       936 non-null    object
 3   Geography    936 non-null    object
 4   Value        930 non-null    float64
dtypes: float64(1), object(4)
memory usage: 36.7+ KB

In [31]:
df.isna().sum()

Fiscal Year    0
Crop           0
Metric         0
Geography      0
Value          6
dtype: int64

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df.shape

(936, 5)

In [34]:
df["Crop"].unique()

array(['Wheat', 'Rice', 'Cotton', 'Sugarcane', 'Maize', 'Gram', 'Jowar',
       'Barley', 'Rapeseed & Mustard', 'Tobacco', 'Sesamum', 'Bajra'],
      dtype=object)

In [35]:
df["Crop"].nunique()

12

In [36]:
df["Metric"].unique()

array(['Area', 'Area Share', 'Production', 'Production Share'],
      dtype=object)

In [37]:
df["Geography"].unique()

array(['Pakistan', 'Punjab'], dtype=object)

In [44]:
df["Start Year"] = (
    df["Fiscal Year"]
    .str[:4]
    .astype(int)
)

df.head()

  Fiscal Year   Crop Metric Geography   Value  Start Year
0     2007-08  Wheat   Area  Pakistan  8550.0        2007
1     2008-09  Wheat   Area  Pakistan  9046.0        2008
2     2009-10  Wheat   Area  Pakistan  9132.0        2009
3     2010-11  Wheat   Area  Pakistan  8901.0        2010
4     2011-12  Wheat   Area  Pakistan  8650.0        2011

In [45]:
df = df[
    [
        "Fiscal Year",
        "Start Year",
        "Crop",
        "Metric",
        "Geography",
        "Value"
    ]
]

In [46]:
df = df.sort_values(
    ["Start Year", "Crop", "Metric", "Geography"]
).reset_index(drop=True)

df.head(20)

   Fiscal Year  Start Year    Crop            Metric Geography    Value
0      2007-08        2007   Bajra              Area  Pakistan    531.0
1      2007-08        2007   Bajra              Area    Punjab    368.0
2      2007-08        2007   Bajra        Area Share    Punjab     69.0
3      2007-08        2007   Bajra        Production  Pakistan    305.0
4      2007-08        2007   Bajra        Production    Punjab    224.0
5      2007-08        2007   Bajra  Production Share    Punjab     73.0
6      2007-08        2007  Barley              Area  Pakistan     91.0
7      2007-08        2007  Barley              Area    Punjab     33.0
8      2007-08        2007  Barley        Area Share    Punjab     36.0
9      2007-08        2007  Barley        Production  Pakistan     87.0
10     2007-08        2007  Barley        Production    Punjab     29.0
11     2007-08        2007  Barley  Production Share    Punjab     33.0
12     2007-08        2007  Cotton              Area  Pakistan   3054.0
13     2007-08        2007  Cotton              Area    Punjab   2425.0
14     2007-08        2007  Cotton        Area Share    Punjab     79.0
15     2007-08        2007  Cotton        Production  Pakistan  11655.0
16     2007-08        2007  Cotton        Production    Punjab   9062.0
17     2007-08        2007  Cotton  Production Share    Punjab     78.0
18     2007-08        2007    Gram              Area  Pakistan   1107.0
19     2007-08        2007    Gram              Area    Punjab    989.0

In [47]:
output_path = r"F:\Mehak Fatima\Farm Analytics\Data\Clean Data Crops\punjab_crop_share_vs_pakistan_cleaned.csv"

df.to_csv(output_path, index=False)

print("Cleaned file saved successfully!")

Cleaned file saved successfully!